Voice
cornell-cup/cs-reminibot pull request #91
Opened 2020-10-12 19:24 UTC by tl676

2020-10-24 16:26 UTC, virenvshah commented on basestation/base_station_interface.py
> +        session_id = self.get_secure_cookie("user_id")
Add comment to either remove or deal with session ids.

2020-11-15 15:52 UTC, slawrence100 requested changes
I had a few installation issues here - TL;DR we'll need to update our installation files / docs first. Here's what happened:

1. I tried running the base station, but it told me that there's no package named `pyaudio`. We should probably add this to the requirements file.
2. I tried `pip install pyaudio`, but that produces this error:
```
src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
```
3. I ended up installing `wheel` before this upon getting a similar error. 
4. I found a solution - [StackOverflow](https://stackoverflow.com/questions/33513522/when-installing-pyaudio-pip-cannot-find-portaudio-h-in-usr-local-include) said to install `portAudio` via homebrew.
5. The `pip install pyaudio` worked fine afterwards

Finally, I don't think the system recognized anything I said - it continuiously said "say something" followed by a timeout even though my system settings say my mic is fine. I noticed that neither Firefox nor Chrome prompted me for mic permissions - maybe that's part of the issue?

edit: The issue with recognition was running the base station in a VSCode terminal, which doesn't allow one to get hardware (i.e. mic) permissions. Once I ran it in Terminal, everything works as expected.

2020-11-28 00:31 UTC, slawrence100 approved these changes
Looks good - Thanks for the installation updates!

2020-12-01 15:02 UTC, kabirwalia8300 approved these changes
Looks good!

2020-12-01 18:29 UTC, ashok-arun approved these changes

2020-12-02 08:41 UTC, merged