Setup page aesthetics
cornell-cup/cs-reminibot pull request #96
Opened 2020-12-05 21:01 UTC by SwathiParthibha

aesthetics changes on the setup page of the gui:
- fixed motor ports dropdown to not cover portions of the gui
- changed color of motor ports dropdown
- fixed motor ports linking and causing page to refresh
- changed color scheme of speech recognition to red
- removed background from vision box

2020-12-06 11:01 UTC, virenvshah requested changes
I think there is a typo but other than that it looks great to me!  The Motor Port dropdown list looks so nice now!

2020-12-06 15:34 UTC, slawrence100 submitted a review, later dismissed
Looks great! Only possible issue I found was the same comment that Viren had.

2020-12-06 17:06 UTC, SwathiParthibha commented on static/gui/static/js/components/AddBot.js
> +    getonData() {
thanks for catching that! when I merged from master I accepted all the incoming changes so it might have just been a typo  - just fixed and pushed

2020-12-06 18:54 UTC, virenvshah approved these changes
Ship It!!!  Looking forward to seeing it in master :)

2020-12-06 20:36 UTC, slawrence100 approved these changes
Thanks for the fix :) Looking forward to seeing this merged in!

2020-12-08 18:29 UTC, kabirwalia8300 approved these changes
Looking forward to these!

2020-12-08 18:30 UTC, merged